import { type NextPage } from "next";
import Head from "next/head";

import styled from "styled-components";

const Seat = styled.div`
  display: flex;
  width: full;
  height: full;
  background-color: #c4b5fd;
  color: white;
  font-size: 2rem;
  justify-content: center;
  align-items: center;
  border-radius: 10%;
  margin: 1rem;
`;

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>🍤</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/logo.svg" />
      </Head>

      <main className="container mx-auto flex min-h-screen flex-col items-center justify-center p-4">
        <h1 className="text-6xl font-bold">This week&apos;s seat</h1>

        {/* Seatings */}
        <div className="seatbox grid h-screen w-full grid-cols-4 grid-rows-4">
          <Seat>Pat</Seat>
          <Seat>Joe</Seat>
          <Seat>Jason</Seat>
          <Seat>Joe</Seat>
          <Seat>Jason</Seat>
          <Seat>Joe</Seat>
          <Seat>Jason</Seat>
          <Seat>Joe</Seat>
          <Seat>Jason</Seat>
          <Seat>Joe</Seat>
          <Seat>Jason</Seat>
          <Seat>Joe</Seat>
          <Seat>Jason</Seat>
          <Seat>Jason</Seat>
          <Seat>Joe</Seat>
          <Seat>Joe</Seat>
        </div>
      </main>
    </>
  );
};

export default Home;
