import { useEffect, useState } from "react";
import Head from "next/head";
import Image from "next/image";

import { Container, Heading } from "@chakra-ui/react";
import styles from "../styles/Home.module.css";

import Layout from "../components/layout/content";
import Paragraph from "../components/paragraph";

export default function Home() {
  const [date, setDate] = useState(new Date());

  useEffect(() => {
    const interval = setInterval(() => setDate(new Date()), 1000);

    return () => {
      clearInterval(interval);
    };
  }, []);

  return (
    <>
      <Head>
        <title>Class Tools</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Layout>
        <main>
          <Container>
            <Heading>{date.toLocaleTimeString()}</Heading>
            <Paragraph>{date.toDateString()}</Paragraph>
          </Container>
        </main>
      </Layout>
    </>
  );
}
